language: java

jdk:
- oraclejdk8

env:
- CI=true

before_script:
- cd example/maven-root
- chmod +x gradlew
 
script:
- ./gradlew check --stacktrace

before_install:
- cd example/maven-root
- chmod +x gradlew

install:
- ./gradlew assemble --stacktrace